import { Droplet, RotateCcw, ZoomIn } from 'lucide-react'

export const propertyControlsConfig = {
  text: [
    {
      key: 'opacity',
      label: 'Opacity',
      min: 0,
      max: 100,
      default: 100,
      step: 1,
      icon: Droplet,
    },
    {
      key: 'rotation',
      label: 'Rotation',
      min: -360,
      max: 360,
      default: 0,
      step: 1,
      icon: RotateCcw,
    },
  ],
  image: [
    {
      key: 'opacity',
      label: 'Opacity',
      min: 0,
      max: 100,
      default: 100,
      step: 1,
      icon: Droplet,
    },
    {
      key: 'rotation',
      label: 'Rotation',
      min: -360,
      max: 360,
      default: 0,
      step: 1,
      icon: RotateCcw,
    },
    {
      key: 'zoom',
      label: 'Zoom',
      min: 10,
      max: 300,
      default: 100,
      step: 1,
      icon: ZoomIn,
    },
  ],
  shape: [
    {
      key: 'opacity',
      label: 'Opacity',
      min: 0,
      max: 100,
      default: 100,
      step: 1,
      icon: Droplet,
    },
    {
      key: 'rotation',
      label: 'Rotation',
      min: -360,
      max: 360,
      default: 0,
      step: 1,
      icon: RotateCcw,
    },
  ],
  background: [
    {
      key: 'opacity',
      label: 'Opacity',
      min: 0,
      max: 100,
      default: 100,
      step: 1,
      icon: Droplet,
    },
    {
      key: 'rotation',
      label: 'Rotation',
      min: -360,
      max: 360,
      default: 0,
      step: 1,
      icon: RotateCcw,
    },
    {
      key: 'zoom',
      label: 'Zoom',
      min: 10,
      max: 300,
      default: 100,
      step: 1,
      icon: ZoomIn,
    },
  ],
}
