-- AlterTable
ALTER TABLE "story_analytics" ADD COLUMN "clicks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "story_analytics" ADD COLUMN "ctr" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "story_analytics" ADD COLUMN "viewability" DOUBLE PRECISION NOT NULL DEFAULT 0;
